# posts account data

curl -H "Content-Type: application/json" -X POST -d '{"balance": "1000", "name": "Fred"}' "http://localhost:3000/accounts"

# gets accounts data

curl "http://localhost:3000/accounts"

# updates account data at specific id, NOTE: replace 'id' in "http://localhost:3000/accounts/id" with the id generated by the previous POST command

curl -H "Content-Type: application/json" -X PUT -d '{"balance": "1500"}' "http://localhost:3000/accounts/ID"

# deletes account data at specific id, NOTE: replace 'id' in "http://localhost:3000/accounts/id" with the id generated by the previous POST command

curl -X DELETE "http://localhost:3000/accounts/ID"

# gets accounts data

curl "http://localhost:3000/accounts"