# posts 4 account data

curl -H "Content-Type: application/json" -X POST -d '{"balance": "500", "name": "Fred"}' "http://localhost:3000/accounts"

curl -H "Content-Type: application/json" -X POST -d '{"balance": "1000", "name": "John"}' "http://localhost:3000/accounts"

curl -H "Content-Type: application/json" -X POST -d '{"balance": "1500", "name": "Jaclyn"}' "http://localhost:3000/accounts"

curl -H "Content-Type: application/json" -X POST -d '{"balance": "2000", "name": "Sonja"}' "http://localhost:3000/accounts"

# gets accounts data

curl "http://localhost:3000/accounts"

# updates account data at specific id, NOTE: replace 'id' in "http://localhost:3000/accounts/id" with the id generated by the previous POST command

#curl -H "Content-Type: application/json" -X PUT -d '{"balance": "1700"}' "http://localhost:3000/accounts/ID"

# gets an account data

#curl "http://localhost:3000/accounts/ID"

# deletes account data at specific id, NOTE: replace 'id' in "http://localhost:3000/accounts/id" with the id generated by the previous POST command

#curl -X DELETE "http://localhost:3000/accounts/ID"

# gets accounts data

#curl "http://localhost:3000/accounts"